---
title: "chat_bot_config"
author: "me"
date: "12/2/2020"
output: html_document
---

Добавить в определения 

Агент - Цифровой чат-бот, аналог живого оператора, принимающего вызов. Агент является связующим звеном между услугами маршрутизации вызова и чат-ботом. При конфигурировании услуги 8-800 терминация вызова на Агенте с соответствующим ID в узлах сценария 8-800 обозначает передачу вызова на чат-бот с указанным Agent ID.


# 3.1.5 Конфигурирование чат-бота

## Создание и конфигурирование Агента

> Для создания Агента используется закладка "настройка чат-бота". Занная закладка доступна при 
> подклюяении ланной услуги Абоненту услуги 8-800

1. Откройте пункт меню "Агент"
2. Выберите + или Создать
3. Заполните форму с базовыми настройками Агента. Вы можете выбрать любое имя Агента.
4. Нажмите "Сохранить"


> Если у вас уже есть сконфигурированный Агент, вы можете последовательно выбрать опции меню "Загрузить" и "Импортировать"

## базовая структура _Диалога_ и по-умолчанию
При создании нового _Агента_ системой будет предложен базовый сценарий Диалога и три _Намерения_ - это базовая структура Диалога по-умолчанию

### _Намерения по умолчанию_:
*Default Welcome Intent*  содержит простые Фразы, такие как "Привет" или "Здравствуйте!" - созданные для обучения системы вариантам первоначального приветствию от пользователя. 

> Конфигурацию Намерения можно изменять в меню "Маршруты по Намерениям" -> "Намерения"

*Default Negative Intent* может быть использован для добавления Фраз, определяющих отрицательный выбор или отказ от выбора "Нет", "До свидания" и тд.

*Default Start Flow* Диалог по умолчанию - может быть основным сценарием Диалога Агента. Для более сложных Агентов может понадобиться более одного Диалога. В простейшем сценарии Диалог начинается с Намерения Defaule Welcome Intent. 

> Логика работы сценария диалога следующая: 

> - Получив сообщение от пользователя, Агент просматривает фразы, заданные на соответствие Намерениям (Intents). Степень соответствия определяется настройкой каждого Намерения - может требоваться прямое соответствие Фразе, соответствие по регулярному выражению, или выбор из классификатора.
> - После выбора Намерения из заданных (в базовом случае задано одно Намерение - Default Welcome Intent), происходит переход на данную Ветвь Диалога, где пользователю может быть отправлено Ответное Сообщение, а также выполнены другие действия

## Конфигурирование ответного сообщения Агента на примере Welcome Intent
Вы можете изменить сообщение, с которым Агент ответит на приветствие пользователя. Для этого:

1. Выберите меню "Агент".
2. Выберите Default Start Flow в секции Диалоги.
3. Найдите Default Welcome Intent в секции маршрут по Намерениям и выберите его.
Откроется панель настроек маршурта по Намерению, выберите раздел "Действия", секция -  "Фиксированный Ответ", и добавьте свое сообщения.
4. Выберите режим выбора ("случайный" будет означать случайный выбор из всего набора сообщений).
5. Закройте панель настройки маршрута по Намерению


## Создание своего Намерения на примере Намерения Местоположения (location Intent)

Намерение определяет желание пользователя перейти по данной ветке диалога. Предположим, что пользователь хочет выяснить местоположение магазина.

В секции "маршрут по намерениям" или в меню "Диалоги":
1. Выбрать пункт + или "Создать" .
2. Выбрать "Намерения"
3. Набрать название Намерения - например, store.location.
4. Ввести соответствующие обучающие фразы:
    Где находится магазин?
    Указания пути
    Скажи мне адрес
    Где мне забрать мой Заказ?
    Как мне туда пройти?    
    Где магазин располагается?
    На какой вы улице?
    Какой ваш адрес?
    Как мне пройти в ваш магазин?
    Где вы?
5. Нажмите "Сохранить"


Теперь необходимо ввести полученное Намерение в Диалог - для этого нужно создать соответствующую ветвь диалога.


1. Выбрать меню "Диалоги"
2. Вырать Default Start Flow.
3. Нажать на первый узел в графе. Это стартовый узел в Default Start Flow.
4. Добавить следующий маршрут по Намерению:
5. Намерение: store.location
6. Раздел "Действия" - оставляем по умолчанию
6. Следующий узел: Store Location
7. Выбрать "Сохранить".

Тестирование диалога "Местоположение магазина"
Для тетсирования созданного диалога:
1. Нажмите кнопку "Тестировать" в меню "Агент" для старта симулятора.
2. Введите "Где находится магазин?"
3. Чат-бо ответит адресом магазина.
4. Закройте симулятор

> Агент выполнил следующие шаги для работы этого диалога:

> - Когда вы ввели запрос, активным сценарием диалога был Default Start Flow, и Агент стал перебирать все маршруты по Намерениям данного диалога.
> - Один из просмотренных маршрутов имеет Намерение store.location. Ваш ввод соответствует этому Намерению _лучше других_, и поэтому он был выбран системой.
> - У этого маршрута в разделе "Действия" не было настроено ответных сообщений или иных действий и поэтому на этом этапе в диалог ничего не добавилось.
> - У данного маршрута настроен Следующий Узел маршрута, и поэтому активным стал узел Store Location.
> - Узел Store Location имеет настроеную Ответную Фразу, поэтому ответное сообщение (адрес) было добавлено в очередь исходящих сообщений .
> - Агент ответил содержимым очереди исходящих сообщений.



## Диалог с использованием формы


## Создание Намерения с параметрами (Slot Filling)


## Действия (Action)



## Тестирование готового Агента









